version: "3.8"

services:
    nodejs:
        build:
            target: production
        command: yarn serve

    mongo:
        volumes:
            - ./data:/data/db

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        networks:
            - backend
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
        links:
            - mongo
        depends_on:
            - mongo