version: "3.8"

services:
    nodejs:
        image: node:16-alpine
        restart: unless-stopped
        command: sh -c "yarn install && yarn run deploy"
        ports:
            - 8080:8080
        working_dir: /nodejs
        # volumes:
        #     - ./express:/nodejs
        networks:
            - read-latte-network
        environment:
            NODE_ENV: ${NODE_ENV}
            NODE_SECRET: ${NODE_SECRET}
            NODE_SESSION_SECRET: ${NODE_SESSION_SECRET}
            MONGO_DB_URI: ${MONGO_DB_URI}
            MONGO_DB_MAIN: ${MONGO_DB_MAIN}
            MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_PASWWORD: ${MONGO_ROOT_PASSWORD}
        depends_on: 
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        networks:
            - read-latte-network
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        networks:
            - read-latte-network
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
        depends_on:
            - mongo
networks:
    read-latte-network:
        driver: bridge