version: "3.8"

services:
    nodejs:
        build:
            context: express
            dockerfile: Dockerfile
        # image: node:16-alpine
        restart: unless-stopped
        working_dir: /app
        command: sh -c "yarn run serve"
        ports:
            - 8080:8080
        volumes:
            - ./express-dup:/app
        networks:
            - api-network
        environment:
            NODE_ENV: ${NODE_ENV}
            NODE_SECRET: ${NODE_SECRET}
            NODE_SESSION_SECRET: ${NODE_SESSION_SECRET}
            MONGO_DB_URI: ${MONGO_DB_URI}
            MONGO_DB_MAIN: ${MONGO_DB_MAIN}
            MONGO_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_PASWWORD: ${MONGO_ROOT_PASSWORD}
        depends_on: 
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        networks:
            - api-network
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        networks:
            - api-network
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
        links:
            - mongo
        depends_on:
            - mongo
networks:
    api-network:
        driver: bridge