version: "3.8"

services:
    nodejs:
        build:
            context: ./express
            dockerfile: Dockerfile
            target: base
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - backend
        environment:
            NODE_ENV: ${NODE_ENV}
            NODE_PORT: ${NODE_PORT}
            NODE_SECRET: ${NODE_SECRET}
            NODE_SESSION_SECRET: ${NODE_SESSION_SECRET}
            MONGO_DB_MAIN: ${MONGO_DB_MAIN}
            MONGO_DB_URI: ${MONGO_DB_URI}
            MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        ports:
            - 27017:27017
        networks:
            - backend
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

networks:
    backend:
        driver: bridge